import numpy as np

# Custos e posições baseados no arquivo Barbie_Arthur.py
CUSTO_TERRENOS = {
    'A': 1,           # Asfalto
    'T': 3,           # Terra
    'G': 5,           # Grama
    'P': 10,          # Paralelepípedo
    'E': float('inf') # Prédios / Obstáculos
}

CASA_BARBIE = (22, 18)

MAPA_TEXTO = """\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
GGPPPPPPPPPPPPPPGGGGPPPPPAGGGGGGGGGGGGGGGG
GGPEEEEEPEEEEEEPGGGGPEEEGAGGGPPPPPPPPPPPGG
GGPEEEEEPEEEEEEPPPPPPEEAAAGGGPGGGGGGGGGPGG
GGPEEPEEPEEEPEEPEEEEGEEAAAGGGPGGGTTTGGGPGG
GGPPPPPPPPPPPPPPPEEEGEEEGAGGGPGGGTTTGGGPGG
GGPTTTTTTTTTTTTPPEEEGGGGGAGGGPGGGTTTGGGPGG
GGPTTTTTTTTTTTTPEEEEGEEEGAGGGPGGGTTTGGGPGG
GGPTTTTGGGGTTTTPPPPPPEEEGAGGGPGGGGGGGGGPGG
GGPTTTTGGGGTTTTPGGGGPEEAAAGGGPPPPPPPPPPPGG
GGPTTTTGGGGTTTTPGGGGPEEEGAGGGGGGGGPGGGGGGG
GGPTTTTTTTTTTTTPGGGGPEEEGAGGGGGGGGPGGGGGGG
GGPTTTTTTTTTTTTPGGGGPGGGGAGGGGGGGGPGGGGGGG
GGPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAA
GGAGGGGGGGGGGGGAGGGGGGGGGAGGGGGGGGGGGGGGGG
GGAGEEEGGEEEEGGAGEEEEEEEGAGEEEEEEEGEEEEEGG
GGAPPEEGGEEEAAAAGEEEEEEEGAGEEEEEEEGEEEEEGG
GGAGEEEGGEEEEGGAGEAEEEAEGAGEEEEAEEGEEAEEGG
GGAGGGGGGGGGGGGAGGAGGGAGGAGGGGGAGGGGGAGGGG
GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG
GGAPPPPPPAGGGGGGGGGGAGGGAGGGGGAGGAGPGGGAGG
GGAPEEEEPAGEEEGGEEEGAGEEAEGEEGAGEAEPEEGAGG
GGAPEEEEPAGEEEGGEEAAAGEEEEGEEGAGEEEPEEGAGG
GGAPEEEPPAAAEEGGEEEGAGGGGGGEAAAGGGGPEAAAGG
GGAPEEEEPAGEEEGGEEEGAGEEEEGEEGAGEEEPEEGAGG
GGAPEEEEPAGEEEGGEEEGAGEEAEGEEGAGEAEPEEGAGG
GGAPPPPPPAGGGGGGGGGGAGGGAGGGGGAGGAGPGGGAGG
GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG
GGAGGGGGGGGAGGGGPGAGPGGGPGAGGGAGGGGPGGGAGG
GGAGEEEEEEGAGEEEPEAEPEEEPEAEGGAGEEEPEEGAGG
GGAGEEAAEEGAGEAEPEEEPEAEPEEEGGAGEEEEEEGAGG
GGAGGGAAGGGAGGAGPGGGPGAGPGGGGGAGGGGGGGGAGG
GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG
GGAGGGGGGGGGGGGGGGGGAGGGGGGPGGGGGGAPPPPAGG
GGAGEEEEEEEEEEEEEEEGAGGGGGGPGGGGGGAPEEPAGG
GGAGEAAAAAAAEEAAAEEGAGGGGGGPGGGGGGAPEEPAGG
GGAGEAEEEEEAEEEEAEEGAPPPPPPPPPPPPPAPPEPAGG
GGAGEAAAAEEAAAAAAEEGAGGGGGGPGGGGGGAPEEPAGG
GGAGEEEEAEEEEEEEEEEGAGGGGGGPGGGGGGAPEEPAGG
GGAGGGGGAGGGGGGGGGGGAGGGGGGPGGGGGGAPPPPAGG
GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"""

def carregar_matriz_mapa():
    """Converte o mapa de string para uma matriz numpy com os custos aplicados."""
    linhas = MAPA_TEXTO.strip().split("\n")
    return np.array([[CUSTO_TERRENOS[char] for char in linha] for linha in linhas])

def eh_posicao_valida(mapa, l, c):
    """Verifica se a coordenada está nos limites e não é um obstáculo."""
    limite_l, limite_c = mapa.shape
    if 0 <= l < limite_l and 0 <= c < limite_c:
        return mapa[l, c] != float('inf')
    return False
